from gareth53.apps.dmigrations.mysql import migrations as m
import datetime
migration = m.InsertRows(
    table_name = 'podcast_episode',
    columns = [u'id', u'title', u'subtitle', u'cover_image', u'episode_number', u'season_number', u'description', u'media_URL', u'primary_keywords', u'secondary_keywords', u'author_name', u'author_email', u'body_html', u'notes_and_errata', u'pub_date', u'enable_comments', u'slug', u'status', u'author_id', u'image_description', u'enhanced_media_URL'],
    insert_rows = ((1L,
  u'Drugs',
  u'In which we discuss tracks with a narcotic theme',
  u'img/podcast/covers/gareth-and-nick008_.jpg',
  8L,
  1L,
  u'In which we discuss songs with a narcotic theme',
  u'http://www.gareth53.co.uk/podcast/mp3/peters-and-senior-episode8-drugs.mp3',
  u'',
  u"<p>Drugs, Mark Linkous, Mark Arm, The Telescopes,High On Fire, Damon Albarn, Sting, Paul Simon, britpop, Oasis, Champagne Supernova, Be Here Now, Apocalypse Now, Noel Gallagher, Liam Gallagher, Jarvis Cocker, Pulp, This Is Hardcore, Steve Albini, Alternative Tentacles, Maximum Rock n Roll, Heroin, Prostitutes, Pornography, Germany, Nitzer Ebb, The Fuzztones, David Gedge, Seamonsters, Columbian Necktie, Ergot, Rapeman, Political Correctness Gone Mad, Fucked Up, Fuck Buttons, Selfish Cunt, Parkinson's Disease, Sleepers, Robert De Niro, Dr Oliver Sachs, Atomizer, The Sound Of Impact, Pig Pile, Shellac, The Adult Net, Brix Smith, The Fall, Nuggets box set, Greg Munford, Psychedelia, Mr Pharmacist, The Other Half, The Horrors, Haight-Ashbury, The Monkees, CBS, Jack Nicholson, Head, Boyce And Heart, Goffin And King, The Porpoise Song, The Locomotion, Pink Floyd, Syd Barrett, Umma Gumma, Dark Side Of The Moon, Cold Turkey, Huddersfield, spliff, hippies, posh students, reefer, blow back, hot rocks, stoned, fags, Mark Owen, Bring It On, Mercury Prize, John Lee Hooker, Liquid Skin, Hut, Virgin, The States, Australia, ATO Records, Crack, Hallucinogens, Mushrooms, The Third Summer Of Love, Muse, Devon, Super Furry Animals, Short Term Memory Loss, Junkie, Habit, Doses, Medicine, Jon Brion, In A Basement Over The Hill, The Windmill Brixton, Hoffman, The King Will Build A Disco, Track And Field, Walking Back To Jesus Parts I &amp; III, Neutral Milk Hotel, Balls, Welcome Home Loser, Jeff Mangum, Olivia Tremor Control, Elephant 6 Holiday Surprise Tour, Engine, First Annual Jeff Mangum Day, Facebook, Rose Wallace Goldaline, The Naked Lunch, William Borroughs, Interzone, Men At Work, Agent Cooper, Twin Peaks, Led Zeppelin, Abbey Road, Jane's Addiction, Justin Warfield, One Inch Punch, She Wants Revenge, Mugwump Jism, Limp Bizkit, De La Soul, Teenage Fanclub, Fugazi Glueman, The Secret Machines Alone Jealous And Stoned, Jesus And Mary Chain, Stoned And Dethroned.</p>",
  u'Gareth Senior',
  u'gareth.senior@hotmail.com',
  u"<p>Two blokes discuss Big Black, The Strawberry Alarm Clock, The Broken Family Band, Elliott Smith, Gomez, and Bomb The Bass. All linked together by a narcotic theme.</p>\r\n<p>Your comments are welcome - so email us with those. And we'll see you next time.</p>",
  u'<p>The cover art is photoshopped from the cover of Everything But The Girl\'s "Walking Wounded" release.</p>\r\n<p>The Britpop documentary is probably John Dower\'s 2003 documentary Live Forever. <a href="http://napalmbutt.googlepages.com/tourdiary.html" target="_blank">The Steve Albini tour diary</a> first appeared in Forced Exposure issue 13.</p>\r\n<p><a href="http://tinyurl.com/albini" target="_blank">The online poker forum</a> where Steve Albini answers questions.</p>\r\n<p>The Dr Oliver Sacks book / De Niro film is Awakenings rather than Sleepers.</p>\r\n<p>Shellac is Steve Albini\'s current band.</p>\r\n<p>John Carter wrote \'Incense &amp; Peppermints\'.</p>\r\n<p>Goffin and King\'s wrote the Loco-motion (1962) before Porpoise Song (1968).</p>\r\n<p>The third \'Summer of Love\' was in 2004.</p>\r\n<p>YouTube hosts <a href="http://uk.youtube.com/watch?v=RxKMPTR0MVA" target="_blank">the Kerry Katona \'car-crash\' interview</a> we mentioned.</p>\r\n<p>Because he "just wants to dance in your tangles" is a reference to the Neutral Milk Hotel  song \'Gardenhead / Leave Me Alone\'.</p>',
  datetime.datetime(2008, 10, 16, 11, 53, 12),
  1,
  u'drugs',
  1L,
  1L,
  u'A pastiche of Everything But The Girl',
  u'http://www.gareth53.co.uk/podcast/mp3/peters-and-senior-episode8-drugs.m4a'),
 (2L,
  u'The Pilot Episode',
  u"OK, let's see if this is fun and if it will work...",
  u'img/podcast/covers/gareth-and-nick001.jpg',
  1L,
  1L,
  u'Testing, testing, one, two, one, two',
  u'http://www.gareth53.co.uk/podcast/mp3/howboutthembears-peters-and-senior-episode1-pilot.mp3',
  u'',
  u"<p>Zaireeka, Shepherd's Bush Empire, Jukebox Jury, Phil Collins, Alternative TV, Patti Smith, The Wonder Stuff, Pat Collier, Elephant 6, Neutral Milk Hotel, Great Lakes, Apples In Stereo, The Camden Falcon, The Spitz (although it wasn't Spitz, it was 93 Feet East), House of Love, Ride, Slowdive, Chapterhouse, The Wharf in Huddersfield, Darkstar, Mercury Rev, The Highbury Garage, Darkside, Spacemen 3, Moonbabies, The Telescopes, Muse, Athlete, Nick Ingram, Editors, Ian Curtis, Grandaddy, The Who, Pink Floyd, Kylie Minogue, The Krazy House in Liverpool, Smashing Pumpkins, Porno For Pyros, Jane's Addiction, David Bowie, Iggy Pop, Phil &amp; Gary &amp; Neville Neville.... phew.</p>",
  u'Gareth Senior',
  u'gareth.senior@hotmail.com',
  u'<p>It\'s a lo-fi concept which we didn\'t think about too hard. We choose three songs, we talk about them. Crucially, it shouldn\'t be a technical nightmare, no complicated post-production. And, even more crucially, it had to be fun.</p>\r\n<p>So this is the pilot. It was easy(ish) from a technical point of view. And it was fun to make.</p>\r\n<p>From listening to this episode it\'s probably quite clear that we hadn\'t done any preparation at all. There\'s a weird edit because I \'forgot\' to actually purchase the recording software and the trial overlays white noise after a certain period of recording.</p>\r\n<p>We also completely forgot to introduce ourselves, so, lest you\'re listening to this and have never met either of us in the real world....</p>\r\n<p>"Record... record? That\'s it we\'re recording...". The first voice you hear, with the Yorkshire accent, is Gareth.</p>\r\n<p>"HELLO LISTENER!". That\'s Nick with the Birmingham twang.</p>',
  u'<p><strong>Will Carruthers</strong> worked in a chipshop and he was in <strong>Freelovebabies</strong> NOT Moonbabies.</p>\r\n<p>The lead singer in The Telescopes was <strong>Stephen Lawrie</strong>.</p>',
  datetime.datetime(2008, 3, 19, 12, 52, 25),
  0,
  u'pilot-episode',
  1L,
  1L,
  u'A pastiche of The Pet Shop Boys, Actually',
  None),
 (3L,
  u'Handclaps & Kiwis',
  u'',
  u'img/podcast/covers/gareth-and-nick002.jpg',
  2L,
  1L,
  u"Nick is a swot and has a theme. Gareth admits to a teenage obsession with the lingerie section of Gratton's Catalogue",
  u'http://www.gareth53.co.uk/podcast/mp3/peters-and-senior-episode2-kiwi.mp3',
  u'',
  u'<p>My sister, <a href="http://wwww.bbc,co.uk/6music" target="_blank">6 Music</a>\'s Matt Everitt, Faith No More, Extreme, Living Color, James Brown, Chicks On Speed, The Dance Exponents, Helen Clark, Neil Finn OBE, Martin Hannett, Gordon Brown, Tony Blair, Agadoo, Slade, <a href="www.bloodshotrecords.com" target="_blank">Bloodshot Records</a>, Audiogalaxy/Rhapsody, Pixies, Black Francis, Kim Deal, The White Stripes, The Stray Cats, <a href="http://www.flyingnun.co.nz" target="_blank">Flying Nun Records</a>, Rough Trade, The Gordons, Sonic Youth, The Wedding Present, Bailterspace, The Brunnettes, Buzzcocks, Sex Pistols, The Clash, Michael Azerrad\'s "Our Band Could Be Your Life: Scenes from the American Indie Underground 1981-1991", Skateboard Magazine, Stiff Little Fingers, Dead Kennedys, Quincy, TV Death, Red Dwarf, The Kia-Ora Advert, SST Recordings, Black Flag\'s "Who\'s Got The 10 1/2?", Kira Roessler, The Pyschedelic Furs\' "Pretty In Pink", Echo &amp; The Bunnymen, Husker Du (the \'Land Speed Record\' album), Brian Eno &amp; Roxy Music, The Beatles, Mike Reid, The Falklands Conflict, Squeeze, "She Will Have Her Way", coloraphobia, Auckland, Tigertailz, Dogs D\'Amour.</p>',
  u'Gareth Senior',
  u'gareth.senior@hotmail.com',
  u"<p>We're back. More songs and some mumbling between them.</p>\r\n<p>We have a shiny little jingle at the beginning and some professional gloss is applied by the use of two shiny new microphone-headphone thingies. We looked a lot like Madonna or Phil Collins did in the eighties - or the call center workers and acne-ridden McDonalds drive-in operatives of today.</p>\r\n<p>Nick has a theme this time out - he did some research and everything. Gareth has no research and no theme. But there's a vaguely sleazy theme - bad sleaze from Anthony Kiedis and good sleaze from The Blacks and a story whereby Gareth admits to a teenage fixation with the lingerie section of Gratton's Catalogue.</p>",
  u'<p>Only a few things up to clear up this time...</p>\r\n<p>Neil Finn has an <strong>OBE</strong>.<br /> John Frusciante was the <strong>fourth</strong> Chili Peppers guitarist.<br /> The Blacks are no longer "split up" they\'ve reunited with the last few years to play a few shows - no new material yet and no official site, but they do have a myspace thingummy: <a href="http://www.myspace.com/blackfamily" target="_blank">myspace.com/blackfamily</a>.<br /> <strong>Little Birdy</strong> covered "Six Months In A Leaky Boat" for "She Will Have Her Way".<br /> And apologies to Mark (home studio), Karl (rhythm guitar), Simon (cardboard Spanish guitar) &amp; John (Yamaha keyboard) for sharing the story.</p>',
  datetime.datetime(2008, 5, 15, 13, 9, 18),
  1,
  u'handclaps-kiwis',
  1L,
  1L,
  u'Dressed as Simon & Garfunkel',
  None),
 (4L,
  u'Mary & The Swedes',
  u'',
  u'img/podcast/covers/gareth-and-nick003.jpg',
  3L,
  1L,
  u'Mary Lorsson and Swedish threads tie things together.',
  u'http://www.gareth53.co.uk/podcast/mp3/peters-and-senior-episode3-swedes.mp3',
  u'',
  u"<p>Kirsty, Matt, Olly, ShoutBox!, DJ Pied Piper &amp; The Master of Ceremonies, Agia Napa.</p>\r\n<p>Juliana Hatfield, Bring It On (movie), The Velvet Underground, Maureen Tucker, My Bloody Valentine, Nirvana, Pixies, John Peel's Festive Fifty, Chumbawamba, Credit To The Nation, Andy Parfitt, Jo Whiley, The Cuban Boys, Scooter.</p>\r\n<p>The Stone Roses, Love Spreads, Nina Persson, Nathan Larsson, The Cardigans, Mark Linkous, Niclas Frisk, Sparklehorse, vivadixiesubmarinetransmissionplot, Daniel Johnstone, Walking The Cow, knickers, Kensington Garden, Camden Dingwalls, Shepherd's Bush Empire, Gran Turismo, Aftenblad, Adam &amp; The Ants.</p>\r\n<p>Uncle Tupelo, Peter Buck, Top Of The Pops, John Peel, Maggie May, Grant Lee Buffalo, Robert Fisher.</p>\r\n<p>ELO, Mika, The Darkness, Jobriath, The Hives, (International) Noise Conspiracy, Soundtrack Of Our Lives, Queen, Eurovision Song Contest.</p>\r\n<p>Robert Fisher,  \tDavid Line,  \tSonic Youth, Pixies, Pavement,  \tIdlewild,  \tUrusei Yatsura,  \tNick Drake,  \tKevin Hendrick,  \tThe 100 Club.</p>\r\n<p>Bergman Rock,  \tPere Ubu,  \tKraftwerk,  \tDavid Tomlinson,  \tJarvis Cocker's Meltdown,  \tDisney,  \tNick Cave,  \tSkye Edwards,  \tEd Harcourt,  \tHal Wilner,  \tPete Doherty,  \tGrace Jones,  \tThe Jungle Book, \tPete Doherty,  \tMary Poppins,  \tRoisin Murphy,  \tBeth Orton,  \tSigmund Freud,  \tShiva,  \tVishnu</p>",
  u'Gareth Senior',
  u'gareth.senior@hotmail.com',
  u'<p>We\'re back. More songs, more mumbling and a brand new feature called "ShoutBox!" (don\'t get exicited, it\'s pathetic and there\'s no prizes).</p>\r\n<p>We both have a theme this time and the first two tracks complement each other nicely, quite by accident. Gareth\'s way too close to his mic in the first link - sorry about the popping and the heavy breathing. Unless that\'s the kind of thing you like.</p>',
  u'<p>Madder Rose\'s Swim was the Number 2 track in <a href="http://www.bbc.co.uk/radio1/johnpeel/festive50s/1990s/1993/" target="_blank">John Peel\'s Festive Fifty in 1993</a>, just behind Chumbawamba &amp; Credit to The Nation.</p>\r\n<p>Intelligencia Vs Cognoscenti was indeed recorded by The Cuban Boys - good call Nick.</p>\r\n<p>BBC Radio One\'s annual event was not (and never was) "In The City", but "Sound City".</p>\r\n<p>The blog comments that inflamed Nick Peter\'s ire regarding Madder Rose "being a poor person\'s Juliana Hatfield" were on <a href="http://becausemidwaystillarentcomingback.blogspot.com" target="_blank">becausemidwaystillarentcomingback.blogspot.com</a> and <a href="http://becausemidwaystillarentcomingback.blogspot.com/2007/06/madder-rose.html" target="_blank">this post</a> in particular.</p>\r\n<p>Nina Persson first saw Sparklehorse perform at a gig in Lund, Sweden. It wasn\'t a festival.</p>\r\n<p>The newspaper that Nina Persson was quoted in regarding the 2nd A Camp album was Dagens Nyheter (the Kultur supplement more specifically)</p>\r\n<p>Mojave is Willard Grant Conspiracys FOURTH album.</p>\r\n<p>Ah yes, the wine:<br /> Hardy\'s Nottage Hill Chardonnay, Aus, 2006 (tropical fruit and melon flavours with an oak character)<br /> Alba Pinot Grigio, Veneto, 2006 (Straw coloured with greenish overtones)<br /> Chateau Pierrousselle Semillon/Sauv Blanc, Bordeaux, 2004 (crisp gooseberry overtones and a hint of fresh toast)</p>\r\n<p>The cover art this time is a pastiche of the cover for Soft Cell\'s "Bedsitter" single. It took ages to glue all that cutlery to the wall, so I hope you appreciate it...</p>',
  datetime.datetime(2008, 6, 4, 13, 13, 26),
  1,
  u'mary-swedes',
  1L,
  1L,
  u'A pastiche of Soft Cell',
  None),
 (5L,
  u'Comedy Covers & Rambling Asides',
  u'In which we dissect the comedy cover version and ramble wildly off-topic',
  u'img/podcast/covers/gareth-and-nick004.jpg',
  4L,
  1L,
  u'In which we dissect the comedy cover version and ramble wildly off-topic',
  u'http://www.gareth53.co.uk/podcast/mp3/peters-and-senior-episode4-covers.mp3',
  u'',
  u"<p>Snow Patrol,  Beyonce Knowles,  Zane Lowe,  Happy Mondays,  Robyn Hitchcock,  Lush,  Middle Of The Road,  14 Iced Bears,  Edison Lighthouse,  The Siddleys,  Pink Floyd,  The Simpsons,  Hullabalooza,  David Bowie,  Bee Gees,  Glass Spider,  Humble Pie,  Steve Marriot,  Small Faces,  Stereophonics,  Joe Eliot,  Def Leppard,  Phil Collins,  Gavin Rossdale,  All Tomorrow's Parties,  Mudhoney,  Lenny Kravitz,  Peel Session,  Jo Whiley,  Fatima Mansions,  Cathal Coughlan,  Bryan Adams,  Wet Wet Wet,  Billy Bragg,  NME,  The Vaselines,  Kaiser Chiefs,  If 6 Was 9,  The Shamen,  The Membranes,  Styler &amp; Baldwin,  Thee Hypnotics,  MC5,  Transvision Vamp,  Sonic Youth,  Red Kross,  Mike Watt,  Minutemens,  The Vaselines,  Burt Bacharach,  Count Indigo,  Mike Flowers Pops,  Fun Lovin' Criminals,  Beverly Hills 90210,  Kylie Minogue,  Miranda Sex Garden,  Jack Pelter &amp; His Sex-Change Chicken,  Kelly Clarkson,  Foreigner,  Devandra Banhardt,  Jim O'Rourke,  Snuff (Punk Gods of the Comedy Cover),  Bran Flakes,  Shake 'n' Vac,  Blankety Blank,  Flibbydibbidydob EP,  Yourgoinghomeinacosmicambience,  Tiffany,  Tommy James &amp; The Shondells,  Billy Idol,  Joan Jett,  Your Mum,  Guns 'n' Wankers,  The Who,  The Wall.</p>",
  u'Gareth Senior',
  u'gareth.senior@hotmail.com',
  u"<p>War! What is it pod four? Yep, it's episode four. This one rambling and unfocused, so... business as usual, despite the long break - you didn't think we'd lose our edge did you!?</p>\r\n<p>We spend more time talking about Snuff (the punk gods of the comedy cover) than we do about the tracks we chose to play. In retrospect, a massive oversight, maybe we'll rectify that in a later episode.</p>\r\n<p>Your comments are welcome - so email us with those. And we'll see you next time.</p>",
  u'<p>The intro/outra is a snippet from Touch Me I\'m Sick by Mudhoney. The cover art is photoshopped from a publicity shot of Siegfried &amp; Roy. Easy tiger...</p>\r\n<p>Peter Frampton appeared in "Homerpalooza", the twenty-fourth episode of The Simpsons\' seventh season and originally aired on May 19, 1996 as part of the season finale.</p>\r\n<p>The internet yields no trace of a Humble Pie Tribute act involving Jo Eliot of Def Leppard, the TV interview may have ben concerning the <a href="http://en.wikipedia.org/wiki/Cybernauts" target="_blank">Cybernauts</a>, which sounds a much more sane endeavour, although obviously the play-thing of retired rock star with too much time and money on his hands.</p>\r\n<p>Dinosaur Jr. performed "You\'re Living All Over Me" in its entirity at Camden\'s Koko on Wednesday 31st August 2005. They didn\'t play "Show Me The Way" :(</p>\r\n<p>Count Indigo never had a top 40 hit single. His version of "Light My Fire" may have been playlisted on Radio 1 however.</p>\r\n<p>The Flaming Lips have also covered Gnarls Berkley\'s "Crazy", Elvis\' "Suspicious Minds", Radiohead\'s "Knives Out" and... "Bohemian Rhapsody"!</p>\r\n<p>Petra Haden performed a song called "Miranda Sex Garden Song" on her 1999 album Imaginaryland</p>\r\n<p>The Mike Watt collaboration that Gareth mentioned is called "<a href="http://www.myspace.com/funanori" target="_blank">Funanori</a>".</p>\r\n<p>Snuff\'s first album was called "Snuffsaidbutgorblimeyguvstonemeifhedidntthrowawobblercha-cha-cha-cha-cha-cha-cha-cha-cha-cha- cha-youregoinghomeinacosmicambience". Upon splitting, members went onto form Guns \'n\' Wankers and Your Mum.</p>\r\n<p>Billy Idol\'s version of "Mony Mony" replaced Tiffany\'s "I Think We\'re Alone Now" at the #1 position on the U.S. Billboard Hot 100 chart toward the end of 1987. Joan Jett\'s cover of "Crimson &amp; Clover" was released in 1982.</p>\r\n<p>The plural of errata is not erratum.</p>',
  datetime.datetime(2008, 8, 19, 14, 22, 17),
  1,
  u'comedy-covers-rambling-asides',
  1L,
  1L,
  u'We are tiger food',
  None),
 (6L,
  u'Time',
  u'Time gentleman please! Six more aural nuggets plucked from our brainiums.',
  u'img/podcast/covers/gareth-and-nick005.jpg',
  5L,
  1L,
  u"Time, time, time, see what's become of us... we introduce an abstract theme.",
  u'http://www.gareth53.co.uk/podcast/mp3/peters-and-senior-episode5-time.mp3',
  u'',
  u"<p>Dave Clark's Time, Iron Maiden 'Two Minutes To Midnight, Paul Simon &amp; Art Garfunkel, Parsley Sage Rosemary and Thyme, Megadeth, In My Hour Of Darkness, Dave Mustaine, Morrissey, Keats, Shelley, Ride, Loz Colbert, Mark Gardener, Andy Bell, Jesus And Mary Chain, Bobby Gillespie, Stone Roses, Ian Brown, John Squire, Oasis, Teenage Fanclub, T Rex, 20th Century Boy, Nirvana School, The Who, Pete Townsend, A Catholic Education, The King, Bandwagonesque, Redd Kross, Phaseshifter, Thirteen, December, Big Star September Gurls, Gere Fenelly, Choo Choo Train, Vevet Crush, Smile, Brian Wilson, Matthew Sweet, Mitch Easter, Gene Clark, The Byrds, Roger McGuinn, Sweetheart Of The Rodeo, Gram Parsons, Grievous Angel, GP, Joy Zipper, Tabitha Tindale, Vinny Cafioso, The Heartlight Set, American Whip, Fifi Trixibell, Scouting For Girls, Joe Lean And The Jing Jang Jong, Clem Snide, The Jam, Down In The Tube Station At Midnight, Paul Weller, Woking, Fugazi, Clem Snide, Ween, Stay Forever, Push The Little Daisies, Chocolate And Cheese, Voodoo Lady, Mr Won't You Please Help My Pony, Freedom of '76, Twelve Country Golden Greats, Rage Against The Machine, U2, Helmet, Soundgarden, Queensryche, Dot Get Too Close To My Fantasy, South Park, Primus, Motorhead, Deftones, Ska, Tool, Maynard James Keenan.</p>",
  u'Gareth Senior',
  u'gareth.senior@hotmail.com',
  u"<p>Episode Five wherein we raise the bar by introducing an abstract concept as a theme. Time.</p>\r\n<p>You'll be glad to know that this hasn't in anyway affected our ability to wander off on a tangent. We had to resort to using the inbuilt mic for this episode so apologies for any inconsistencies in clarity and volume.</p>\r\n<p>Your comments are welcome - so email us with those. And we'll see you next time.</p>",
  u'<p>The cover art is photoshopped from the cover of 10cc\'s \'Changing Faces: The Very Best of 10cc/Godley &amp; Creme\'.</p>\r\n<p>The Megadeth song is called \'In My Darkest Hour\' rather than \'In My Hour Of Darkness\' and is from the band\'s third album \'So Far, So Good... So What?\' (1988) This album also features their shocking cover of Anarchy In The UK where Dave Mustaine changes the lyric "another council tenancy" to "another cunt-like tendency". Nice.</p>\r\n<p>Rides first three EPs were Ride (the red rose one), Play (the yellow daffodils) and Fall (grey with penguins). The poor man\'s "You Can\'t Always Get What You Want" from Carnival Of Light was called "I Don\'t Know Where It Comes From".</p>\r\n<p>The Teenage Fanclub blatant Big Star rip off Nick was thinking of was "What You Do To Me".</p>\r\n<p>Vinny Cafioso broke his wrist in November 2007.</p>\r\n<p>Counting official Ween albums is difficult as some were tape only releases on obscure labels. The band were active from 1984 and GodWeenSatan: The Oneness came out in 1990 and The Pod was released in 1991. White Pepper came out in 2000.</p>\r\n<p>There are no obvious Deftones references on White Pepper and the covers bear no obvious similarities. Nick blames the cold and flu medication.</p>',
  datetime.datetime(2008, 9, 18, 14, 23, 58),
  1,
  u'time',
  1L,
  1L,
  u'A pastiche of Godley & Creme',
  None),
 (7L,
  u'Grunge',
  u"What is this word 'grunge'? What does it mean? We have few ideas, but it does prompt some good tuneage.",
  u'img/podcast/covers/gareth-and-nick006.jpg',
  6L,
  1L,
  u"What is this word 'grunge'? What does it mean? We have few ideas, but it does prompt some good tuneage.",
  u'http://www.gareth53.co.uk/podcast/mp3/peters-and-senior-episode6-grunge.mp3',
  u'',
  u"<p>Kelly Canary, Kurt Cobain, Bobcat Goldthwaite, Sub Pop, Jack Endino, Sex Pistols, The Great Rock And Roll Swindle, Nirvana, L7, Tad, Love Battery, Ossie Ardilles, Pancake Day, James Belushi, The Dwarves, Seattle, Screaming Trees, Imaginary Records, The Lemonheads, Sonic Youth, Dinsoaur Jr, Buffalo Tom, Butthole Surfers, Big Black, BBC Late Show, No Nirvana, Pearl Jam, Smashing Pumpkins, Rage Against The Machine, R.E.M., Half A World Away, Peter Buck, The Stone Roses, Sugar, Copper Blue, Nevermind, Brit Pop, Noel Gallagher, I Hate Myself And I Want To Die, Live Forever, Blur, Northside, Chicken Rhythms, Jane's Addiction, Negative Creep, Super Fuzz Big Muff, Appetite For Destruction, Epic, Faith No More, Pixies, Bleach, Negative Creep, Charles Peterson, Fugazi, Uncle Tupelo, Island Records, Fopp Records, Franz Ferdinand, Izzy Stradlin, Dinosaur Jr, Where You Been, Black Grape, Song For Louise Post, Chris Savage, Veruca Salt, Nine Inch Nails, Soundgarden, Mudhoney, Heatmiser, Elliott Smith, Pond, Tad, Feeder, The Melvins, Sonic Youth, U-Men, Velvet Revolver, Linkin Park, Jimmy Eat World, Bowling For Soup, Afghan Whigs, Rage Against The Machine, Malfunkshun, Alice In Chains, Bush, Candlebox, The Lemonheads, Motley Crue, Guns n' Roses, Hole, Foo Fighters, Stone Temple Pilots, Silverchair, Daisy Chainsaw, Audioslave, Presidents Of The United States Of America, Gas Huffer, Heart Shaped Box, Scott Litt, Andy Wallace, L7, Killdozer, Die Kreuzen, Touch And Go, Punch N Judy, Clear Black Paper, SST, Hey Big Brother, Rare Earth, Our Love Will Still Be There, The Troggs, Beat Happening, The Postal Service, Low, Sleater Kinney, All Hands On The Bad One, In The Woods.</p>",
  u'Gareth Senior',
  u'gareth.senior@hotmail.com',
  u"<p>Two blokes discuss Dickless, Green River, The Monkeywrench, The Buck Pets, The Screaming Trees, and The Fluid. They also talk nonsense about what grunge means without coming to any definite conclusions.</p>\r\n<p>Your comments are welcome - so email us with those. And we'll see you next time.</p>",
  u'<p>The cover art is photoshopped from the cover of The Carpenters album Singles 1969 - 1981.</p>\r\n<p>The Dickless double a side single was \'I\'m A Man\' / \'Saddle Tramp\'.</p>\r\n<p>The toga reference should of course be to John Belushi, not his brother James.</p>\r\n<p>Nirvana\'s first single was a cover of \'Love Buzz\' by Shocking Blue.</p>\r\n<p>Searchin\' appeared on the Glitterhouse album Motor City Madness, it is now available on the Green River Rehab Doll / Come On Down two-fer CD.</p>\r\n<p>Youtube has <a href="http://www.youtube.com/watch?v=HDRz3H30NmY" target="_blank">The Stone Roses\' infamous Late Show appearance</a> of which we speak.</p>\r\n<p>Sugar\'s \'Copper Blue\' was released in 1992.</p>\r\n<p>Nirvana\'s \'I Hate Myself And I Want To Die\' appears on the b-side of Pennyroyal Tea and on the compilation album The Beavis and Butt-Head Experience (1993).</p>\r\n<p>Northside\'s Chicken Rhythms was indeed killed by Nirvana\'s Nevermind.</p>\r\n<p>Mudhoney\'s Superfuzz Big Muff came out in 1988.</p>\r\n<p>Charles Peterson\'s photography is well worth a look. It can be seen here: <a href="http://www.charlespeterson.net" target="_blank">www.charlespeterson.net</a>.</p>\r\n<p>The Fluid a brief album discography: Punch N Judy (1986), Clear Black Paper (1988),  Freak Magnet EP (1989), Roadmouth (1989), Glue (1990), Purplemetalflakemusic (1993). Buy them all if you can.</p>',
  datetime.datetime(2008, 10, 3, 14, 28, 37),
  1,
  u'grunge',
  1L,
  1L,
  u'A pastiche of The Carpenters',
  None),
 (8L,
  u'Fire!',
  u'',
  u'img/podcast/covers/gareth-and-nick007.jpg',
  7L,
  1L,
  u"We discuss songs with the theme of 'fire' including Sparklehorse, Brendan Benson, The Telescopes & That Petrol Emotion",
  u'http://www.gareth53.co.uk/podcast/mp3/peters-and-senior-episode7-fire.mp3',
  u'',
  u"<p>The Crazy World Of Arthur Brown Fire, Jimi Hendrix Experience Fire, Sparklehorse Vivadixiesubmarinetransmissionplot, David Fridmann, Mercury Rev, Mark Linkous, Polly Harvey, Valium, Codeine, Heroin, dirt bikes, Nico, John Cale, Nina Perrson, Daniel Johnston, Virginia, Shepherd's Bush Empire, Neutral Milk Hotel, ULU, The Velvet Underground, bongo solo, The Byrds, The Perfect Needle, I Scream She Falls, Boo Radleys, Flying, Snub TV, shoegazing, jazz, Ride, Slowdive, the scene that celebrates itself, Spaceman 3, My Bloody Valentine, Loop Heaven's End, melodica, The Wannadies, Kurt Dahle, Carl Newman / AC Newman, Neko Case, Dan Bejar, Destroyer, Broken Social Scene, Arcade Fire, Godspeed You Black Emperor!, Superconductor, Zampano, Swanlake, Vancouver Nights, The Immaculate Machine, The Evaporators, Challengers, The HMV Playlist CD, Brendan Benson Folksinger, The White Stripes,, Virgin, V2, The Raconteurs, Jack White, Mood Elevators, Laserbeam, Steve Albini, Secret Name, glockenspiel, xylophone, Mimi Parker, Alan Spahawk, Kramer, Duluth, Mormon Rock, Christian Rock, David Fridmann, The Undertones, Talking Heads, Television, Babble, Big Decison, Dance, Genius Move, Hey Venus, Sensitize, Tingle, 8:15 From Manchester, Steve Mack, Scott Litt, Chemicrazy, REM, Radio Song, Out of Time, KRS One, Koogat Records, The Boston Arms.</p>",
  u'Gareth Senior',
  u'gareth.senior@hotmail.com',
  u"<p>Two blokes discuss Sparklehorse, The Telescopes, The New Pornographers, Brendan Benson, Low and That Petrol Emotion. All linked together by the elemental buzzword 'fire'.</p>\r\n<p>Your comments are welcome - so email us with those. And we'll see you next time.</p>",
  u'<p>The cover art is photoshopped from the cover of  The Jesus &amp; Mary Chain\'s "Barbed Wire Kisses" album release.</p>\r\n<p>The second Sparklehorse album is Good Morning Spider.</p>\r\n<p>The Telescopes formed in 1987.</p>\r\n<p>The White Stripes have covered  Brendan Benson\'s Good To Me</p>\r\n<p>It\'s \'the scene that celebrated itself\' rather than \'the scene that supported itself\'.</p>\r\n<p>The third That Petrol emotion album is called End of the Millennium Psychosis Blues rather than Post Millennium Psychosis Blues.</p>',
  datetime.datetime(2008, 10, 16, 14, 30, 58),
  1,
  u'fire',
  1L,
  1L,
  u'A pastiche of Jesus & The Mary Chain',
  None),
 (9L,
  u'B-Sides',
  u'Celebrating the long-lost art of the flipside',
  u'img/podcast/covers/gareth-and-nick009.jpg',
  9L,
  1L,
  u'Two fellas discuss the long lost art of the flipside track.',
  u'',
  u'',
  u'<p>B-sides, digital formats, maxi single, 3 inch CD singles, Walkman, Adorable, Coventry, Sistine Chapel Ceiling, Creation, Robert Dillam, Seasick Martyr, shoegazing, Lush, Ride, Sunshine Smile, Radiohead, My Bloody Valentine, Thom Yorke, Piotr Fijalkowski, C86, Psychedelic Furs, Ian McCulloch, Echo And The Bunnymen, Scratch Acid, b-side compilations, cover versions, Suede, My Insatiable One, Sci-Fi Lullabies, To The Birds, Bernard Butler, The Smiths, Dog Man Star, jazz infused hip hop, xylophone solos, mandolins, Maggie May, Reason To Believe, Tim Hardin, house music, Saint Etienne, Foxbase Alpha, Billy Liar, Fatboy Slim, Lemonjelly, indie dance, iTunes, Bob Stanley, Pete Wiggs, eBay. London Conversations, Like A Motorway, Sarah Cracknell, My Bloody Valentine, Slow, Isn\'t Anything, The Birthday Party, Geek, Sunny Sundae Smile, glide guitar, Strawberry Wine, Ecstasy, Bilinda Butcher, country, Loveless, Thorn, reformations, Primal Scream, The Roundhouse, rose-tinted spectacles, Blur, Graham Coxon, Don\'t Look Back, Parklife, \'Blur\', Damon Albarn, Gorillaz, G-Sides, Monkey - Journey To The West, vinyl, storage, iTunes abuse report, copyright, last.fm, Spotify, MySpace music, remixes, Lou Reed \'Walk On The Wild Side\', hip hop, Deee -Lite, Q-Tip, De La Soul, Prima Scream \'Loaded\', Stone Roses, Happy Mondays, Jesus Jones, A Tribe Called Quest, I Left My Wallet In El Segundo, Snub TV, YouTube, Jungle Brothers, Queen Latifah, De La Soul, 3 Feet High And Rising, A Tribe Called Quest, People\'s Instinctive Travels And The Paths Of Rhythm, Three Is The Magic Number, Bob Dorough, Ice T, Public Enemy, N.W.A, Ice Cube, The Church \'Under The Milkyway\' Starfish Donnie Darko, Richard Kelly, Lenny Kravitz, Ice T, Curtis Mayfield, Tone Loc, Easy-E, NWA, CPO, Marvin Gaye, What\'s Goin On, Isaac Hayes, Duran Duran, The Cardigans, Pooh Song, Pixies, Wave Of Mutilation (UK Surf Mix), James, Stand, Getting Away With It All (All Messed Up), Teenage Fan Club, Goody Goody Gumdrops, PJ Harvey, Wang Dang Doodle, Red Hot Chili Peppers, Soul To Squeeze, Mudhoney Pump It Up,  Prince, Erotic City, Dinosaur Jr., Quicksand, David Bowie, Nirvana, Sliver, Rain, The Beatles, Paperback Writer, I\'m Free, Get Off My Cloud, Rolling Stones, Soup Dragons, Neutral Milk Hotel, <a href="http://bsidesrus.blogspot.com/" target="_blank">bsidesrus.blogspot.com</a>, Kung Fu Fighting, How Soon Is Now, The Smiths, William, It Was Really Nothing, Hatful Of Hollow, The World Won\'t Listen, Louder Than Bombs, Acquiesce, Oasis, the Gallagher brothers, Some Might juiceSay, Roll With It.</p>',
  u'',
  u'',
  u'<p>his episode we\'re discussing B-sides. What makes a good B-side? Why don\'t we get those cute mini CDs any more? Is Lenny Kravitz a black man? Why xylophone solos rock and mandolin solos suck. We also spend a lot of time taking about hip-hop despite, and we freely admit this, knowing virtually nothing about the genre. As per usual we come to no meaningful conclusions, but that\'s simply not the point.<br /><br />Apologies for the scratchiness of the Tribe Called Quest track and the needle jump on the Curtis Mayfield track.<br /><br />Your comments are welcome - email us with those. And we\'ll see you next time with episode ten! (who\'d ha thunk we\'d get this far? not us). It\'ll be a round-up episode and we\'ll be playing all those acts that we\'re banging on about but have yet to play.<br /><br />Uh, before I forget, we started <a href="http://thenickandgarethpodcast.blogspot.com/" target="_blank">a blog</a> where we occasionally expand on stuff that gets mentioned in the podcast.</p>',
  u'<p>The cover art is photoshopped from the cover of INXS\' "<a href="http://en.wikipedia.org/wiki/Kick_%28album%29" target="_blank">Kick</a>" release from 1987.</p>\r\n<p>The \'<a href="http://en.wikipedia.org/wiki/Dog_man_star" target="_blank">Dog Man Star</a>\' track that doesn\'t feature any contribution from Bernard Butler and that Gareth refers to rather unkindly is \'The Power\'.</p>\r\n<p>Sarah Cracknell\'s solo album was called <a href="http://en.wikipedia.org/wiki/Lipslide" target="_blank">Lipslide</a>. It was released in 1997.</p>\r\n<p>The B-side on the 7-inch release of My Bloody Valentine\'s \'You Made Me Realise\' was \'Slow\'.</p>\r\n<p>\'Under The Milky Way\' was released in 1988. \'Starfish\' was The Church\'s sixth album. To date, they have recorded 17 studio albums.</p>\r\n<p>The second Superfly movie is called \'<a href="http://www.imdb.com/title/tt0070753/" target="_blank">Super Fly T.N.T.</a>\'.</p>',
  datetime.datetime(2009, 1, 8, 14, 12),
  1,
  u'b-sides',
  1L,
  1L,
  u"a pastich of INXS' Kick album cover",
  u'')),
    delete_ids = [1, 2, 3, 4, 5, 6, 7, 8, 9]
)
