from gareth53.apps.dmigrations.mysql import migrations as m
import datetime
migration = m.InsertRows(
    table_name = 'podcast_artist',
    columns = [u'id', u'name', u'official_URL', u'wikipedia_URL', u'slug'],
    insert_rows = ((1L,
  u'Big Black',
  u'',
  u'http://en.wikipedia.org/wiki/Big_Black',
  u'big-black'),
 (2L,
  u'Elliott Smith',
  u'',
  u'http://en.wikipedia.org/wiki/Elliott_smith',
  u'elliott-smith'),
 (3L,
  u'Bomb The Bass',
  u'',
  u'http://en.wikipedia.org/wiki/Bomb_The_Bass',
  u'bomb-bass'),
 (4L, u'Gomez', u'', u'http://en.wikipedia.org/wiki/Gomez_(band)', u'gomez'),
 (5L,
  u'The Broken Family Band',
  u'http://www.thebrokenfamilyband.com/',
  u'',
  u'broken-family-band'),
 (6L,
  u'The Strawberry Alarm Clock',
  u'',
  u'http://en.wikipedia.org/wiki/The_Strawberry_Alarm_Clock',
  u'strawberry-alarm-clock'),
 (7L,
  u'Curtis Mayfield',
  u'',
  u'http://en.wikipedia.org/wiki/Curtis_Mayfield',
  u'curtis-mayfield'),
 (8L,
  u'My Bloody Valentine',
  u'',
  u'http://en.wikipedia.org/wiki/My_Bloody_Valentine_(band)',
  u'my-bloody-valentine'),
 (9L,
  u'A Tribe Called Quest',
  u'',
  u'http://en.wikipedia.org/wiki/A_tribe_called_quest',
  u'tribe-called-quest'),
 (10L,
  u'St. Etienne',
  u'',
  u'http://en.wikipedia.org/wiki/Saint_Etienne_(band)',
  u'st-etienne'),
 (11L,
  u'Adorable',
  u'',
  u'http://en.wikipedia.org/wiki/Adorable_(band)',
  u'adorable'),
 (12L,
  u'The Church',
  u'',
  u'http://en.wikipedia.org/wiki/The_Church_(band)',
  u'the-church'),
 (13L,
  u'Sparklehorse',
  u'',
  u'http://en.wikipedia.org/wiki/Sparklehorse',
  u'sparklehorse'),
 (14L,
  u'The Telescopes',
  u'',
  u'http://en.wikipedia.org/wiki/The_telescopes',
  u'the-telescopes'),
 (15L, u'Pixies', u'', u'', u'pixies'),
 (16L, u'The Velvet Underground', u'', u'', u'the-velvet-underground'),
 (17L, u'Neutral Milk Hotel', u'', u'', u'neutral-milk-hotel'),
 (18L, u'Redd Kross', u'', u'', u'redd-kross'),
 (19L,
  u'The New Pornographers',
  u'',
  u'http://en.wikipedia.org/wiki/The_New_Pornographers',
  u'the-new-pornographers'),
 (20L,
  u'That Petrol Emotion',
  u'',
  u'http://en.wikipedia.org/wiki/That_Petrol_Emotion',
  u'that-petrol-emotion'),
 (21L, u'Low', u'', u'http://en.wikipedia.org/wiki/Low_(band)', u'low'),
 (22L, u'Dickless', u'', u'', u'dickless'),
 (23L,
  u'Green River',
  u'',
  u'http://en.wikipedia.org/wiki/Green_River_(band)',
  u'green-river'),
 (24L,
  u'Screaming Trees',
  u'',
  u'http://en.wikipedia.org/wiki/Screaming_Trees',
  u'screaming-trees'),
 (25L,
  u'The Buck Pets',
  u'',
  u'http://en.wikipedia.org/wiki/The_Buck_Pets',
  u'the-buck-pets'),
 (27L,
  u'The Monkeywrench',
  u'',
  u'http://en.wikipedia.org/wiki/The_Monkey_Wrench',
  u'the-monkeywrench'),
 (28L,
  u'The Fluid',
  u'',
  u'http://en.wikipedia.org/wiki/The_Fluid',
  u'the-fluid'),
 (29L,
  u'Levitation',
  u'',
  u'http://en.wikipedia.org/wiki/Levitation_%28band%29',
  u'levitation'),
 (30L,
  u'The Olivia Tremor Control',
  u'',
  u'http://en.wikipedia.org/wiki/Olivia_Tremor_Control',
  u'the-olivia-tremor-control'),
 (31L,
  u'Birdland',
  u'',
  u'http://en.wikipedia.org/wiki/Birdland_%28band%29',
  u'birdland'),
 (32L, u'Ride', u'', u'http://en.wikipedia.org/wiki/Ride_(band)', u'ride'),
 (33L,
  u'Teenage Fanclub',
  u'',
  u'http://en.wikipedia.org/wiki/Teenage_Fanclub',
  u'teenage-fanclub'),
 (34L,
  u'Superchunk',
  u'',
  u'http://en.wikipedia.org/wiki/Superchunk',
  u'superchunk'),
 (35L,
  u'Velvet Crush',
  u'',
  u'http://en.wikipedia.org/wiki/Velvet_Crush',
  u'velvet-crush'),
 (36L,
  u'Joy Zipper',
  u'',
  u'http://en.wikipedia.org/wiki/Joy_Zipper',
  u'joy-zipper'),
 (37L, u'Ween', u'', u'http://en.wikipedia.org/wiki/Ween', u'ween'),
 (38L, u'Cud', u'', u'http://en.wikipedia.org/wiki/Cud_(band)', u'cud'),
 (39L,
  u'Dinosaur Jr.',
  u'',
  u'http://en.wikipedia.org/wiki/Dinosaur_Jr',
  u'dinosaur-jr'),
 (40L,
  u'Ben Folds FIve',
  u'',
  u'http://en.wikipedia.org/wiki/Ben_folds',
  u'ben-folds-five'),
 (41L,
  u'Shonen Knife',
  u'',
  u'http://en.wikipedia.org/wiki/Shonen_Knife',
  u'shonen-knife'),
 (42L,
  u'The New Fast Automatic Dafodils',
  u'',
  u'http://en.wikipedia.org/wiki/New_FADS',
  u'the-new-fads'),
 (43L,
  u'Petra Haden',
  u'',
  u'http://en.wikipedia.org/wiki/Petra_Haden',
  u'petra-haden'),
 (44L,
  u'Madder Rose',
  u'',
  u'http://en.wikipedia.org/wiki/Madder_Rose',
  u'madder-rose'),
 (45L, u'A Camp', u'', u'http://en.wikipedia.org/wiki/A_Camp', u'a-camp'),
 (46L,
  u'The Willard Grant Conspiracy',
  u'',
  u'http://en.wikipedia.org/wiki/Willard_Grant_Conspiracy',
  u'the-willard-grant-conspiracy'),
 (47L,
  u'bob hund',
  u'http://www.bobhund.nu/',
  u'http://en.wikipedia.org/wiki/Bob_hund',
  u'bob-hund'),
 (48L,
  u'Seafood',
  u'',
  u'http://en.wikipedia.org/wiki/Seafood_%28band%29',
  u'seafood'),
 (49L,
  u'The Ark',
  u'',
  u'http://en.wikipedia.org/wiki/The_Ark_%28band%29',
  u'the-ark'),
 (50L,
  u'Red Hot Chili Peppers',
  u'http://www.redhotchilipeppers.com/',
  u'',
  u'red-hot-chili-peppers'),
 (51L,
  u'The Exponents',
  u'http://www.myspace.com/theeexponents',
  u'',
  u'the-exponents'),
 (52L,
  u'Split Enz',
  u'',
  u'http://en.wikipedia.org/wiki/Split_Enz',
  u'split-enz'),
 (53L,
  u'The Clean',
  u'',
  u'http://en.wikipedia.org/wiki/The_Clean',
  u'the-clean'),
 (54L,
  u'Black Flag',
  u'',
  u'http://en.wikipedia.org/wiki/Black_Flag_(band)',
  u'black-flag'),
 (55L, u'The Blacks', u'http://www.myspace.com/blackfamily', u'', u'blacks'),
 (56L,
  u'The Flaming Lips',
  u'http://www.flaminglips.com/',
  u'',
  u'the-flaming-lips'),
 (57L,
  u'Dr. Phibes & The House Of Wax Equations',
  u'',
  u'http://en.wikipedia.org/wiki/Dr_phibes_and_the_house_of_wax_equations',
  u'dr-phibes-and-the-house-wax-equations'),
 (58L, u'New Electrics', u'', u'', u'new-electrics'),
 (59L, u'Various', u'', u'', u'various'),
 (60L,
  u'Brendan Benson',
  u'',
  u'http://en.wikipedia.org/wiki/Brendan_benson',
  u'brendan-benson')),
    delete_ids = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60]
)
