from gareth53.apps.dmigrations.mysql import migrations as m
import datetime
migration = m.InsertRows(
    table_name = 'articles_article',
    columns = [u'id', u'title', u'slug', u'body_html', u'pub_date', u'status', u'category_id', u'pod_promos_id'],
    insert_rows = ((1L,
  u'RSS Feeds',
  u'rss-feeds',
  u'<h2>Main Feeds</h2>\r\n<p>There\'s the vanilla RSS feeds for the blog and for the podcast</p>\r\n<ul>\r\n<li><a href="http://www.gareth53.co.uk/blog/posts.xml" target="_blank">Blog RSS feed</a></li>\r\n<li><a href="http://www.gareth53.co.uk/podcast/podcast-feed.xml" target="_blank">Podcast RSS feed</a></li>\r\n</ul>\r\n<p>You can also subscribe to blog posts on a per category basis. So, if you\'re interested in film reviews but not all that javascript, Django and HTML malarky, well, feel free to do so.</p>\r\n<h2>Blog Category Feeds</h2>\r\n<ul>\r\n<li><a href="http://www.gareth53.co.uk/blog/category/development.xml" target="_blank">\'development\'</a></li>\r\n<li><a href="http://www.gareth53.co.uk/blog/category/design.xml" target="_blank">\'design\'</a></li>\r\n<li><a href="http://www.gareth53.co.uk/blog/category/tellybox.xml" target="_blank">\'tellybox\'</a></li>\r\n<li><a href="http://www.gareth53.co.uk/blog/category/football.xml" target="_blank">\'football\'</a></li>\r\n<li><a href="http://www.gareth53.co.uk/blog/category/rant.xml" target="_blank">\'rant\'</a></li>\r\n<li><a href="http://www.gareth53.co.uk/blog/category/film.xml" target="_blank">\'film\'</a></li>\r\n<li><a href="http://www.gareth53.co.uk/blog/category/personal.xml" target="_blank">\'personal\'</a></li>\r\n<li><a href="http://www.gareth53.co.uk/blog/category/music.xml" target="_blank">\'music\'</a></li>\r\n<li><a href="http://www.gareth53.co.uk/blog/category/radio.xml" target="_blank">\'radio\'</a></li>\r\n<li><a href="http://www.gareth53.co.uk/blog/category/podcast.xml" target="_blank">\'podcast\'</a></li>\r\n</ul>\r\n<h2>RSS Help</h2>\r\n<p>If you don\'t know what this mysterious \'RSS\' is - it\'s an acronym for "Really Simple Syndication". There\'s an introduction to what it is, what it does and how to use it below.</p>\r\n<ul>\r\n<li><a href="http://en.wikipedia.org/wiki/RSS_(file_format)" target="_blank">Wikipedia definition of RSS</a></li>\r\n<li><a href="http://news.bbc.co.uk/sport1/hi/help/rss/default.stm" target="_blank">Help pages on bbc.co.uk Sport section</a></li>\r\n</ul>',
  datetime.datetime(2009, 1, 19, 22, 47, 38),
  1L,
  3L,
  1L),
 (2L,
  u'Podcasting Help',
  u'podcasting-help',
  u'<p>The word "podcasting" is a portmanteau of "ipod" and "broadcasting".</p>\r\n<p>Podcasts are like radio programmes but on the interweb. Subscribe to a podcast adn a new episode will be downloaded when it\'s published.</p>\r\n<p>Although podcasts are like radio, it\'s incredibly important they shouldn\'t feature as high production values as radio programmes, they shouldn\'t be slick, they shouldn\'t feature adverts or professional DJs or voice artists. That\'s cheating. Also, if a podcast appears to have been made by chopping up the best pieces of a proper radio show, well that\'s a serious offence and baby jesus will, somewhere, be shedding a single, opaque tear.</p>\r\n<p>As you can see, it\'s complicated (and, although I shouldn\'t be telling you this... it involves copious use of smoke, mirrors, secret trapdoors and twins).</p>\r\n<p>Most people refer to the iTunes for their podcasting needs. But you can use other software (<a href="http://juicereceiver.sourceforge.net" target="_blank">Juice</a> is a good one).</p>\r\n<p>You\'ll need the feed to subscribe to the podcast: <a href="http://www.gareth53.co.uk/podcast/podcast-feed.xml" target="_blank">here it is</a>.</p>\r\n<p>If you need more sensible help, try these:</p>\r\n<ul>\r\n<li><a href="http://www.bbc.co.uk/radio/help/faq/what_is_a_podcast.shtml" target="_blank">BBC Radio\'s Podcasting FAQ</a></li>\r\n</ul>\r\n<p>&nbsp;</p>',
  datetime.datetime(2009, 1, 20, 13, 24, 44),
  1L,
  1L,
  5L),
 (3L,
  u'About Me',
  u'about-me',
  u'<p>Hi. I\'m Gareth Senior. I live and work in London although I\'m originally from West Yorkshire.</p>\r\n<p>I\'ve lived in North London since February 2000, during that time I\'ve worked as a designer / web developer for Capital Radio Group, GCap Media plc, BBC Worldwide, EMAP Automotive and Global Radio.</p>\r\n<p>Sites I\'ve worked on:</p>\r\n<ul>\r\n<li><a href="http://www.xfm.co.uk" target="_blank">Xfm</a></li>\r\n<a href="http://www.xfm.co.uk" target="_blank"> </a>\r\n<li><a href="http://www.capitalradio.co.uk" target="_blank">Capital Radio</a></li>\r\n<a href="http://www.capitalradio.co.uk" target="_blank"> </a>\r\n<li><a href="http://www.topgear.com" target="_blank">Top Gear</a></li>\r\n<a href="http://www.topgear.com" target="_blank"> </a>\r\n<li><a href="http://www.radiotimes.com" target="_blank">Radio Times</a></li>\r\n<li><a href="http://www.classicfm.co.uk" target="_blank">Classic FM</a></li>\r\n<li><a href="http://www.bbcgoodfood.com" target="_blank">Good Food Magazine</a></li>\r\n<li><a href="http://www.bbcgardenersworld.com" target="_blank">Gardener\'s World</a></li>\r\n<li><a href="http://www.hit40uk.com" target="_blank">Hit40UK</a></li>\r\n<li><a href="http://www.bbcgirltalk.com" target="_blank">Girl Talk Magazine</a></li>\r\n<li><a href="http://www.maxpower.co.uk" target="_blank">Max Power</a></li>\r\n<li><a href="http://www.lro.com" target="_blank">Land Rover Owner</a></li>\r\n<li><a href="http://www.thebrokenfamilyband.com" target="_blank">The Broken Family Band</a></li>\r\n</ul>\r\n<h2>Elsewhere On The Internets</h2>\r\n<p>You can find me in the following places:</p>\r\n<ul>\r\n<li><a href="http://www.flickr.com/photos/gareth53/" target="_blank">Flickr</a></li>\r\n<li><a href="http://twitter.com/gareth53" target="_blank">Twitter</a></li>\r\n<li><a href="http://www.last.fm/user/gareth53" target="_blank">Last.fm</a></li>\r\n<li><a href="http://www.facebook.com" target="_blank">Facebook</a></li>\r\n<li><a href="http://www.linkedin.com/in/garethsenior" target="_blank">linkedIn</a></li>\r\n<li><a href="http://delicious.com/gareth53" target="_blank">delicious</a></li>\r\n</ul>\r\n<h2>Contacting Me</h2>\r\n<p>Drop me an email: gareth53[at]gmail.com.</p>',
  datetime.datetime(2009, 2, 4, 14, 15, 18),
  1L,
  3L,
  4L),
 (4L,
  u'About The Site',
  u'about-this-site',
  u'<p>This site has been built using the Django Framework.</p>\r\n<p>There\'s a joke in the Django community that the very first thing a deveoper duils with the framework is a blogging application. Who am I to break this trend ;) There\'s no commenting. Because I had a blogspot blog and nobody ever commented on that, so I decided not to bother. There\'s a Django app that I might get around to installing one day. But not today.</p>\r\n<p>It\'s all hand-rolled, not because this is the right thing to do, but because it was a learning exercise.</p>\r\n<h2>Browser Support</h2>\r\n<p>This site has been successfully tested in the browers listed as A-grade browsers in Yahoo\'s Graded Browser Support Policy, although not all OS versions.</p>\r\n<p>This includes the following browsers on OSX 10.5.5 and Windows XP where available:</p>\r\n<ul>\r\n<li>Firefox 2 &amp; 3</li>\r\n<li>Opera 9</li>\r\n<li>Safari 3</li>\r\n<li>Internet Explorer 6 &amp; 7</li>\r\n</ul>\r\n<p>If you find a bug, be a love and let me know. Ta.</p>\r\n<h2>Some bits &amp; pieces</h2>\r\n<p>On the front end I\'m using (and heartily recommending):</p>\r\n<ul>\r\n<li>YUI Font Reset CSS</li>\r\n<li>jQuery</li>\r\n</ul>\r\n<p>I\'m also using the TinyMCE WYSIWYG plug-in for my admin, but it\'s glitchy as hell and I can\'t find my way to recommending it. Sorry!</p>\r\n<h2>Hosting</h2>\r\n<p>It\'s hosted by the fellas at <a href="http://www.webfaction.com" target="_blank">WebFaction</a>. I did fancy hosting it in the UK and I looked at <a href="http://www.mampi.co.uk/" target="_blank">Mampi Hosting</a>, but, in the end, I went down the tried and trusted (and cheap!) path.</p>\r\n<p><a href="http://djangofriendly.com/hosts/" target="_blank">DjangoFriendly.com</a> was instrumental in the process of shopping aound.</p>',
  datetime.datetime(2009, 2, 13, 14, 2, 33),
  1L,
  3L,
  2L),
 (5L,
  u'About Nick & Gareth',
  u'about-nick-and-gareth',
  u'<p>Nick Peters was born in a crossfire hurricane.</p>\r\n<p>Gareth Senior used to work on the docks. Working nine to five, down on his luck, phew! that ws rough.</p>',
  datetime.datetime(2009, 2, 21, 13, 20, 53),
  1L,
  1L,
  6L)),
    delete_ids = [1, 2, 3, 4, 5]
)
